### PR TITLE
Added support for maven classifier

### PR DESCRIPTION
**Pull request by mathieuboniface**
This Pull Request allow plugin users to define a classifier for their artifacts.

### CODE REVIEW

**Comment by jbye** [comment]
Definitely useful. Thanks for the pull request :+1:

**Comment by mathieuboniface** [comment]
Is there any plan to release this plugin on Maven central ?

**Comment by jbye** [comment]
Definitely. For our internal development we are using our own Nexus instance, which is why we haven't gone forward with the deploy to central just yet. I'll look in to getting it sorted next week.

**Comment by jbye** [comment]
@mathieuboniface FYI, I have just finished staging the plugin in the Sonatype OSS repository.

**Comment by mathieuboniface** [comment]
:+1:  good news :)

**Pull request merged**
